// Run all fixtures through the current solvers and write outputs to
// tests/golden.js. Run ONCE before refactoring; the goldens are then frozen so
// any behavior change will fail tests.

const fs = require('fs');
const path = require('path');
const { NonogramSolver, AquariumSolver, GalaxiesSolver, BinairoSolver, ShikakuSolver, YinYangSolver, SlitherlinkSolver } = require('../solver.js');
const fixtures = require('./fixtures/puzzles.js');

function solveNonogram(p) {
  return new NonogramSolver(p.rowClues, p.colClues).solve(null);
}
function solveAquarium(p) {
  return new AquariumSolver(p.rowClues, p.colClues, p.regionMap, p.rows, p.cols).solve(null);
}
function solveGalaxies(p) {
  return new GalaxiesSolver(p.stars, p.rows, p.cols).solve(null);
}
function solveBinairo(p) {
  BinairoSolver.clearSolutionCache();
  return new BinairoSolver({
    rows: p.rows, cols: p.cols, givens: p.givens,
    comparisonClues: p.comparisonClues || [],
  }).solve();
}
function solveShikaku(p) {
  ShikakuSolver.clearSolutionCache();
  return new ShikakuSolver({ rows: p.rows, cols: p.cols, clues: p.clues }).solve();
}
function solveYinYang(p) {
  YinYangSolver.clearSolutionCache();
  return new YinYangSolver({ rows: p.rows, cols: p.cols, task: p.task }).solve();
}
function solveSlitherlink(p) {
  SlitherlinkSolver.clearSolutionCache();
  return new SlitherlinkSolver({ width: p.cols, height: p.rows, task: p.task }).solve();
}

const raw = {
  nonogramDiagonal5: solveNonogram(fixtures.nonogramDiagonal5),
  nonogramCorners3:  solveNonogram(fixtures.nonogramCorners3),
  aquariumTiny:      solveAquarium(fixtures.aquariumTiny),
  aquariumLarge:     solveAquarium(fixtures.aquariumLarge),
  galaxiesTiny:      solveGalaxies(fixtures.galaxiesTiny),
  galaxiesSmall:     solveGalaxies(fixtures.galaxiesSmall),
  binairo6x6:        solveBinairo(fixtures.binairo6x6),
  binairoPlus6x6:    solveBinairo(fixtures.binairoPlus6x6),
  shikaku5x5:        solveShikaku(fixtures.shikaku5x5),
  yinyang6x6:        solveYinYang(fixtures.yinyang6x6),
  slitherlink5x5:    solveSlitherlink(fixtures.slitherlink5x5),
};

// Strip any non-deterministic fields (timing, internal counters) before writing.
function clean(result) {
  if (!result || typeof result !== 'object') return result;
  if ('horizontal' in result && 'vertical' in result) {
    // Slitherlink shape.
    const { solved, horizontal, vertical, error } = result;
    return { solved, horizontal, vertical, error: error || null };
  }
  const { solved, grid, error } = result;
  return { solved, grid, error: error || null };
}

const cleaned = {};
for (const k of Object.keys(raw)) cleaned[k] = clean(raw[k]);

const out =
  '// AUTO-GENERATED by tests/capture.js — do not edit by hand.\n' +
  'module.exports = ' + JSON.stringify(cleaned, null, 2) + ';\n';

fs.writeFileSync(path.join(__dirname, 'golden.js'), out);
console.log('Wrote tests/golden.js with', Object.keys(cleaned).length, 'entries.');
for (const k of Object.keys(cleaned)) {
  console.log(`  ${k}: solved=${cleaned[k].solved}${cleaned[k].error ? ' error=' + cleaned[k].error : ''}`);
}
