// Run all fixtures through the current solvers and write outputs to
// tests/golden.js. Run ONCE before refactoring; the goldens are then frozen so
// any behavior change will fail tests.

const fs = require('fs');
const path = require('path');
const { NonogramSolver, AquariumSolver, GalaxiesSolver } = require('../solver.js');
const fixtures = require('./fixtures/puzzles.js');

function solveNonogram(p) {
  return new NonogramSolver(p.rowClues, p.colClues).solve(null);
}
function solveAquarium(p) {
  return new AquariumSolver(p.rowClues, p.colClues, p.regionMap, p.rows, p.cols).solve(null);
}
function solveGalaxies(p) {
  return new GalaxiesSolver(p.stars, p.rows, p.cols).solve(null);
}

const raw = {
  nonogramDiagonal5: solveNonogram(fixtures.nonogramDiagonal5),
  nonogramCorners3:  solveNonogram(fixtures.nonogramCorners3),
  aquariumTiny:      solveAquarium(fixtures.aquariumTiny),
  aquariumLarge:     solveAquarium(fixtures.aquariumLarge),
  galaxiesTiny:      solveGalaxies(fixtures.galaxiesTiny),
  galaxiesSmall:     solveGalaxies(fixtures.galaxiesSmall),
};

// Strip any non-deterministic fields (timing, internal counters) before writing.
function clean(result) {
  if (!result || typeof result !== 'object') return result;
  const { solved, grid, error } = result;
  return { solved, grid, error: error || null };
}

const cleaned = {};
for (const k of Object.keys(raw)) cleaned[k] = clean(raw[k]);

const out =
  '// AUTO-GENERATED by tests/capture.js — do not edit by hand.\n' +
  'module.exports = ' + JSON.stringify(cleaned, null, 2) + ';\n';

fs.writeFileSync(path.join(__dirname, 'golden.js'), out);
console.log('Wrote tests/golden.js with', Object.keys(cleaned).length, 'entries.');
for (const k of Object.keys(cleaned)) {
  console.log(`  ${k}: solved=${cleaned[k].solved}${cleaned[k].error ? ' error=' + cleaned[k].error : ''}`);
}
